### ISSUE TITLE
1 is not a supported code page

### ISSUE THREAD

**Issue by rquinio** [rquinio/PortraitBuilder#11]
```
2018-06-28 22:35:20,980 FATAL Program - Fatal error.System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(Stream stream)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at PortraitBuilder.Engine.Loader.UnzipDLCs(List`1 dlcs) in c:\Users\Romain\git\PortraitBuilder\PortraitBuilder\Engine\Loader.cs:line 128
   at PortraitBuilder.Engine.Loader.LoadDLCs() in c:\Users\Romain\git\PortraitBuilder\PortraitBuilder\Engine\Loader.cs:line 106
   at PortraitBuilder.UI.PortraitBuilderForm.loadDLCs(Boolean clean) in c:\Users\Romain\git\PortraitBuilder\PortraitBuilder\UI\PortraitBuilderForm.cs:line 144
   at PortraitBuilder.UI.PortraitBuilderForm.load(Boolean clean) in c:\Users\Romain\git\PortraitBuilder\PortraitBuilder\UI\PortraitBuilderForm.cs:line 125
   at PortraitBuilder.UI.PortraitBuilderForm..ctor() in c:\Users\Romain\git\PortraitBuilder\PortraitBuilder\UI\PortraitBuilderForm.cs:line 77
   at PortraitBuilder.Program.StartUI(String[] args) in c:\Users\Romain\git\PortraitBuilder\PortraitBuilder\Program.cs:line 85
```

**Comment by rquinio** [comment]
@Gloweye I've just released [v3.0-RC.2](https://github.com/rquinio/PortraitBuilder/releases/tag/v3.0-RC.2) which contains the commit you mentioned, could you please check whether the issue is gone ? 

Note .NET required version has been upgraded from 4.5 to [4.6](https://www.microsoft.com/en-US/download/details.aspx?id=48130) which comes pre-installed with Windows 10.
